export const mockProductData = [
  {
    id: "serialnoa",
    name: "air macbook",
    price: 1119990,
    company: "macbook",
    colors: ["#22D3EF", "#ff0000", "#000000"],
    description: "",
    category: "laptop",
    featured: true,
    stock: 6,
    reviews: 70,
    stars: 5,
    image: [
      {
        id: "randomid1",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/laptop-flat-vector-icon-illustration-1572362782",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid2",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/laptop-flat-vector-icon-illustration-1572362782",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid3",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/laptop-flat-vector-icon-illustration-1572362782",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid4",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/laptop-flat-vector-icon-illustration-1572362782",
        filename: "prod-4.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "serialnob",
    name: "galaxy w20",
    price: 311999,
    company: "samsung",
    colors: ["#22D3EF", "#ff0000", "#000000"],
    description: "",
    category: "mobile",
    featured: true,
    stock: 6,
    review: 60,
    stars: 4.4,
    image: [
      {
        id: "randomid21",
        width: 1080,
        height: 650,
        url: " https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid22",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid23",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid24",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-4.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "serialnoc",
    name: "nokia",
    price: 12000,
    company: "nokia",
    colors: ["#22D3EF", "#ff0000", "#000000"],
    description: "",
    category: "mobile",
    featured: true,
    stock: 10,
    review: 68,
    stars: 3.4,
    image: [
      {
        id: "randomid31",
        width: 1080,
        height: 650,
        url: " https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid32",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid33",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid34",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-4.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "serialnod",
    name: "titan raga",
    price: 12000,
    company: "titan",
    colors: ["#22D3EF", "#000000"],
    description: "",
    category: "watch",
    featured: false,
    stock: 10,
    review: 68,
    stars: 3.4,
    image: [
      {
        id: "randomid41",
        width: 1080,
        height: 650,
        url: " https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid42",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid43",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "randomid44",
        width: 1080,
        height: 650,
        url: "https://www.shutterstock.com/image-vector/concept-touch-screen-smartphone-blank-interface-1433190200",
        filename: "prod-4.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
];
